name: GitHub CI

on:
-   push
-   pull_request

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: windows-2019
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

                TARGET_CPU:
                -   x86
                -   amd64

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3
            with:
                submodules: true

        -   name: Install
            shell: cmd
            run: |
                set CONFIGURATION=${{matrix.CONFIGURATION}}
                call doxyrest\ci\github-actions\set-env.bat msvc16 ${{matrix.TARGET_CPU}}
                call doxyrest\ci\github-actions\install-windows.bat

        -   name: Build and test
            shell: cmd
            run: |
                set CONFIGURATION=${{matrix.CONFIGURATION}}
                set THIS_DIR=%CD%
                set THIS_DIR_CMAKE=%THIS_DIR:\=/%

                call doxyrest\ci\github-actions\set-env.bat msvc16 ${{matrix.TARGET_CPU}}

                mkdir %DOWNLOAD_DIR%\expat\build
                cd %DOWNLOAD_DIR%\expat\build
                cmake .. %CMAKE_CONFIGURE_FLAGS% %EXPAT_CMAKE_FLAGS% || exit
                cmake --build . %CMAKE_BUILD_FLAGS% || exit

                cd %THIS_DIR%
                echo set (EXPAT_INC_DIR %DOWNLOAD_DIR_CMAKE%/expat/lib) >> paths.cmake
                echo set (EXPAT_LIB_DIR %DOWNLOAD_DIR_CMAKE%/expat/build/%CONFIGURATION%) >> paths.cmake

                mkdir build
                cd build
                cmake .. %CMAKE_CONFIGURE_FLAGS% || exit
                cmake --build . %CMAKE_BUILD_FLAGS% || exit
                ctest --output-on-failure -C %CONFIGURATION% || exit

    linuxBuild:
        name: Linux Build
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

                TARGET_CPU:
                -   x86
                -   amd64

                COMPILER:
                -   clang
                -   gcc

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3
            with:
                submodules: true

        -   name: Install
            shell: bash
            run: |
                export TARGET_CPU=${{matrix.TARGET_CPU}}
                source ./doxyrest/ci/github-actions/install-linux.sh

        -   name: Build and test
            shell: bash
            run: |
                THIS_DIR=$(pwd)
                export CC=$(which ${{matrix.COMPILER}})
                export CXX=$(which ${{matrix.COMPILER}}++)

                mkdir build
                cd build
                cmake .. -DTARGET_CPU=${{matrix.TARGET_CPU}} -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
                make
                ctest --output-on-failure

    macOsBuild:
        name: macOS Build
        runs-on: macos-11
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3
            with:
                submodules: true

        -   name: Install
            shell: bash
            run: |
                source ./doxyrest/ci/github-actions/install-osx.sh

        -   name: Build and test
            shell: bash
            run: |
                THIS_DIR=$(pwd)

                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
                make
                ctest --output-on-failure
